server:
  port: 9000
spring:
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  spring:
    config:
      activate:
        on-profile: local
  profiles:
    active:
    include: secret
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      location: '${custom.image.url}'
      max-request-size: 500MB
      max-file-size: 500MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            redirect-uri: '${custom.site.baseUrl}/oauth2/code/{registrationId}'
            scope:
              - email
              - profile

cloud:
  aws:
    s3:
      bucket: '${cloud.aws.s3.bucket}'
      url: '${cloud.aws.s3.url}'
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: '${cloud.aws.s3.credentials.accessKey}'
      secretKey: '${cloud.aws.s3.credentials.secretKey}'

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace

domain: '${custom.image.domain}'
